[ADD]Added a button to show pending vouchers from Customer's Form view
druidoo/druidoo-addons pull request #28
Opened 2020-01-22 11:38 UTC by krunal267

Task URL:

https://www.druidoo.io/web#view_type=form&model=project.task&id=1408&active_id=1408&menu_id=237

2020-01-22 13:00 UTC, ivantodorovich requested changes

2020-01-22 13:00 UTC, ivantodorovich commented on pos_voucher/models/res_partner.py
> +        action['display_name'] = _('Pending Vouchers')
I prefer not to change the display_name, let's just remove this line

```suggestion
```

2020-01-22 13:00 UTC, ivantodorovich commented on pos_voucher/models/res_partner.py
> +            lambda v: v.state in ('validated', 'partially_consumed')).ids)]
Do we have filters in the search view?
I think, in terms of usability, it's better to use context to filter results.

instead of changing the domain, I think you can send a context like this:

```
{'search_default_validated': 1, 'search_default_partially_consumed': 1, 'search_default_partner_id': self.id }
```

I didn't test this, and it asumes you have the validated and partially_consumed filters defined on the search view (real names might be different).

But, basically, what I'd like is that the action returns the view without any domain, and some filters applied.

2020-01-22 13:00 UTC, ivantodorovich commented on pos_voucher/models/res_partner.py
> +            lambda v: v.state in ('validated', 'partially_consumed')).ids)]
If you do this, you can probably remove the `voucher_ids` field

2020-01-23 04:11 UTC, krunal267 commented on pos_voucher/models/res_partner.py
> +            lambda v: v.state in ('validated', 'partially_consumed')).ids)]
Okay, noted it. I will do the changes.

2020-01-24 15:48 UTC, merged